version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ccvm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ccvm
      POSTGRES_USER: ccvm
      POSTGRES_PASSWORD: ChangeMeStrongPassword
      TZ: Europe/Berlin
    volumes:
      - ccvm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ccvm -d ccvm"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ccvm-redis
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    image: ccvm-backend:0.4.0
    container_name: ccvm-backend
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_NAME: ccvm
      DB_USER: ccvm
      DB_PASS: ChangeMeStrongPassword
      TZ: Europe/Berlin
    volumes:
      - ./backend:/app
    ports:
      - "8088:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ./frontend
    image: ccvm-frontend:0.4.0
    container_name: ccvm-frontend
    restart: unless-stopped
    ports:
      - "8090:80"
    depends_on:
      - backend

  nuclei:
    image: projectdiscovery/nuclei:latest
    container_name: ccvm-nuclei
    restart: unless-stopped
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ccvm_scanner_data:/data

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: ccvm-gotenberg
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  ccvm_postgres_data:
  ccvm_scanner_data:
