"""add discovered urls

Revision ID: 05c7a5c03d2f
Revises: 42f5da4e9ff6
Create Date: 2026-07-10 08:27:46.065294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c7a5c03d2f'
down_revision: Union[str, None] = '42f5da4e9ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'url', name='uq_urls_domain_url')
    )
    op.create_index(op.f('ix_urls_customer_id'), 'urls', ['customer_id'], unique=False)
    op.create_index(op.f('ix_urls_domain_id'), 'urls', ['domain_id'], unique=False)
    op.create_index(op.f('ix_urls_host_id'), 'urls', ['host_id'], unique=False)
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_host_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_domain_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_customer_id'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
