"""extend findings model

Revision ID: 0dd9cfec116e
Revises: 7a1064760a7b
Create Date: 2026-07-06 06:19:00.849515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd9cfec116e'
down_revision: Union[str, None] = '7a1064760a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('scanner', sa.String(length=100), nullable=False))
    op.add_column('findings', sa.Column('template_id', sa.String(length=255), nullable=True))
    op.add_column('findings', sa.Column('name', sa.String(length=512), nullable=False))
    op.add_column('findings', sa.Column('host', sa.String(length=512), nullable=True))
    op.add_column('findings', sa.Column('matched_at', sa.String(length=1024), nullable=True))
    op.add_column('findings', sa.Column('remediation', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('reference', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('cvss_score', sa.String(length=50), nullable=True))
    op.add_column('findings', sa.Column('raw_json', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('findings', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('findings', 'cve',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint('findings_scan_id_fkey', 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'jobs', ['job_id'], ['id'])
    op.drop_column('findings', 'scan_id')
    op.drop_column('findings', 'title')
    op.drop_column('findings', 'recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('findings', sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key('findings_scan_id_fkey', 'findings', 'scans', ['scan_id'], ['id'])
    op.alter_column('findings', 'cve',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('findings', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('findings', 'status')
    op.drop_column('findings', 'raw_json')
    op.drop_column('findings', 'cvss_score')
    op.drop_column('findings', 'reference')
    op.drop_column('findings', 'remediation')
    op.drop_column('findings', 'matched_at')
    op.drop_column('findings', 'host')
    op.drop_column('findings', 'name')
    op.drop_column('findings', 'template_id')
    op.drop_column('findings', 'scanner')
    op.drop_column('findings', 'job_id')
    # ### end Alembic commands ###
