"""extend jobs for discovery

Revision ID: 42f5da4e9ff6
Revises: d30e8832cba9
Create Date: 2026-07-08 08:48:45.477058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42f5da4e9ff6'
down_revision: Union[str, None] = 'd30e8832cba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.alter_column('jobs', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('jobs', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('jobs', 'worker',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('ix_jobs_uuid', table_name='jobs')
    op.create_unique_constraint(None, 'jobs', ['uuid'])
    op.create_foreign_key(None, 'jobs', 'domains', ['domain_id'], ['id'])
    op.drop_column('jobs', 'finished_at')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.create_index('ix_jobs_uuid', 'jobs', ['uuid'], unique=True)
    op.alter_column('jobs', 'worker',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('jobs', 'message',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'uuid',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('jobs', 'domain_id')
    # ### end Alembic commands ###
